const jokes = [
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "I used to play piano by ear, but now I use my hands.",
    "Why don’t eggs tell jokes? They’d crack each other up.",
    "How does a penguin build its house? Igloos it together.",
    "Want to hear a joke about construction? I'm still working on it.",
    "Why did the bicycle fall over? It was two tired.",
    "I don't trust stairs. They're always up to something.",
    "What do you call fake spaghetti? An impasta!",
    "Why was the math book sad? It had too many problems.",
    "Did you hear about the restaurant on the moon? Great food, no atmosphere.",
    "Why can't you give Elsa a balloon? Because she will let it go.",
    "How do you organize a space party? You planet.",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "I'm on a seafood diet. I see food and I eat it.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why can't you hear a pterodactyl in the bathroom? Because the 'P' is silent.",
    "Did you hear about the kidnapping at the playground? They woke up.",
    "Why did the coffee file a police report? It got mugged.",
    "How does Moses make his coffee? Hebrews it.",
    "Why don't oysters share their pearls? Because they are shellfish.",
    "I'm reading a book about teleportation. It's bound to take me places.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "What’s orange and sounds like a parrot? A carrot.",
    "Why do cows wear bells? Because their horns don’t work.",
    "What time did the man go to the dentist? Tooth-hurty.",
    "Why did the scarecrow get promoted? He was outstanding in his field.",
    "What do you call a belt made of watches? A waist of time.",
    "Why don’t seagulls fly over the bay? Because then they’d be bay-gulls.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "What do you call an alligator in a vest? An investigator.",
    "Why did the cookie go to the hospital? Because it felt crummy.",
    "What do you call a bear with no teeth? A gummy bear.",
    "How do you make holy water? You boil the hell out of it.",
    "Why did the melon jump into the lake? It wanted to be a watermelon.",
    "How does a snowman get around? By riding an 'icicle'.",
    "What's brown and sticky? A stick.",
    "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    "Why was the broom late? It swept in.",
    "What kind of tree fits in your hand? A palm tree.",
    "Why did the mushroom go to the party alone? Because he's a fungi.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "What's red and smells like blue paint? Red paint.",
    "Why did the banana go to the doctor? It wasn't peeling well.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "How does the moon cut his hair? Eclipse it.",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets.",
    "Why are fish so smart? Because they live in schools.",
    "What do you call a boomerang that won’t come back? A stick.",
    "How does a taco say grace? Lettuce pray.",
    "What’s the best way to watch a fly-fishing tournament? Live stream.",
    "Why did the computer go to the doctor? It had a virus.",
    "What did one plate say to the other? Lunch is on me.",
    "Why was the math teacher sad? She had too many problems.",
    "Why don't sharks eat clowns? Because they taste funny.",
    "What’s a skeleton’s least favorite room in the house? The living room.",
    "Why did the tomato blush? Because it saw the salad dressing.",
    "Why are ghosts bad at lying? Because they are too transparent.",
    "How does a dog stop a video? By hitting the paws button.",
    "Why did the cowboy get a dachshund? Someone told him to get a long little doggie.",
    "Why did the bicycle stand still? It was two-tired.",
    "What’s Forrest Gump’s password? 1forest1.",
    "Why did the belt go to jail? It held up a pair of pants.",
    "Why do vampires seem sick? They’re always coffin.",
    "How does a scientist freshen their breath? With experi-mints.",
    "What do you get when you cross a snowman and a dog? Frostbite.",
    "What kind of shoes do ninjas wear? Sneakers.",
    "Why did the gym close down? It just didn’t work out.",
    "How do you catch a squirrel? Climb up a tree and act like a nut.",
    "Why did the lifeguard kick the elephants out of the pool? They kept dropping their trunks.",
    "How do you make a tissue dance? Put a little boogie in it.",
    "What kind of music do mummies listen to? Wrap music.",
    "Why did the scarecrow keep getting promoted? Because he was outstanding in his field.",
    "How do you organize a space party? You planet.",
    "Why do birds fly south in the winter? Because it’s faster than walking.",
    "What did the fish say when it hit the wall? Dam.",
    "What do you call a factory that makes good products? A satisfactory.",
    "Why did the stadium get hot after the game? All the fans left.",
    "How does a train eat? It goes chew chew.",
    "How does a penguin build its house? Igloos it together.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "What’s the difference between a piano and a fish? You can tune a piano, but you can’t tuna fish.",
    "Why are elevator jokes so classic and good? They work on many levels.",
    "Why don't crabs give to charity? Because they’re shellfish.",
    "How do you make a lemon drop? Just let it fall.",
    "How do you find Will Smith in the snow? You look for fresh prints.",
    "Why don’t some fish play piano? Because they’re afraid of the scales.",
    "What’s a skeleton’s least favorite thing to do? Go to a 'fun'ction.",
    "Why do bananas never get lonely? Because they hang out in bunches.",
    "What kind of shorts do clouds wear? Thunderwear.",
    "Why was the big cat disqualified from the race? Because it was a cheetah.",
    "What do you call an elephant that doesn't matter? An irrelephant.",
    "Why did the belt go to school? To get a new waist of knowledge.",
    "What did one plate say to the other plate? 'Tonight, dinner's on me.'",
    "Why was the math book sad? It had too many problems.",
    "What do you call a cow with no legs? Ground beef.",
    "Why was the picture sent to jail? It was framed.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "I'm reading a book about anti-gravity. It's impossible to put down!",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "Why did the bicycle fall over? It was two-tired!",
    "What do you call fake spaghetti? An impasta!",
    "I used to play piano by ear, but now I use my hands.",
    "Why was the math book sad? It had too many problems.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I used to be a baker, but I couldn't make enough dough.",
    "What do you call a fish with no eyes? Fsh.",
    "Why was the belt arrested? For holding up a pair of pants.",
    "What do you call a dinosaur with an extensive vocabulary? A thesaurus.",
    "Why don't eggs tell jokes? They'd crack each other up.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "How does a penguin build its house? Igloos it together.",
    "I'm on a whiskey diet. I've lost three days already.",
    "What's brown and sticky? A stick.",
    "Why don't oysters donate to charity? Because they're shellfish.",
    "How does a scientist freshen her breath? With experi-mints.",
    "Why did the coffee file a police report? It got mugged.",
    "Why was the broom late? It swept too much.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "I would tell you a construction joke, but I'm still working on it.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "How do you organize a space party? You planet.",
    "Why did the computer go to the doctor? It had a virus.",
    "Why can't a nose be 12 inches long? Because then it would be a foot.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "How do you make holy water? You boil the hell out of it.",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why did the banker switch careers? He lost interest.",
    "What's orange and sounds like a parrot? A carrot.",
    "What do you call a pile of cats? A meowtain.",
    "Why don't seagulls fly over the bay? Because then they'd be bay-gulls.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Why can't you hear a pterodactyl go to the bathroom? Because the P is silent.",
    "I'm reading a book on teleportation. It's bound to take me places!",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "I used to have a job at a calendar factory but I got the sack because I took a couple of days off.",
    "Why did the man put his money in the blender? He wanted to make some liquid assets.",
    "Why do cows have hooves instead of feet? Because they lactose.",
    "What do you get if you cross an angry sheep and a moody cow? An animal that’s in a baaaad moooood.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "What's a skeleton's least favorite room in the house? The living room.",
    "Why did the scarecrow keep getting promoted? Because he was outstanding in his field.",
    "Why are frogs so happy? They eat whatever bugs them.",
    "How do you catch a squirrel? Climb into a tree and act like a nut.",
    "What did the buffalo say to his son when he left for college? Bison.",
    "Why don't dinosaurs drive cars? Because they're extinct.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "How does a penguin build its house? Igloos it together.",
    "Why did the barber win the race? He knew all the shortcuts.",
    "How does a snowman get around? By riding an “icicle.”",
    "What did the judge say when the skunk walked into the courtroom? Odor in the court!",
    "What’s a skeleton’s least favorite food? Spare ribs.",
    "How do you make a tissue dance? You put a little boogie in it.",
    "Why don't you ever see giraffes hiding in trees? Because they're so good at it.",
    "Why did the music teacher need a ladder? To reach the high notes.",
    "What do you call a boomerang that doesn’t come back? A stick.",
    "What did the left eye say to the right eye? Between us, something smells.",
    "Why don’t skeletons ever go trick or treating? Because they have no body to go with.",
    "I used to be a train driver, but I got sidetracked.",
    "What did the big flower say to the little flower? Hey, bud!",
    "Why do melons have weddings? Because they cantaloupe!",
    "Why don’t some fish use the internet? Because they're afraid of getting caught in the net.",
    "What did the fisherman say to the magician? Pick a cod, any cod.",
    "What did the grape do when it got stepped on? Nothing but let out a little wine.",
    "What’s Forrest Gump’s password? 1forest1.",
    "Why do bananas never feel lonely? Because they hang out in bunches.",
    "What do you call a factory that makes okay products? A satisfactory.",
    "How do you find Will Smith in the snow? You look for fresh prints.",
    "What do you get when you cross a vampire with a snowman? Frostbite.",
    "Why don't vampires like garlic? It’s too intense for their taste.",
    "What do you call a cow with no legs? Ground beef.",
    "Why don't you give Elsa a balloon? Because she will let it go!",
    "Why do ducks have tail feathers? To cover their butt quacks.",
    "What did the baby corn say to the mama corn? Where’s popcorn?",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "How do you organize a fantastic party in space? You planet.",
    "How do you know the ocean is friendly? It waves.",
    "What did one snowman say to the other snowman? Do you smell carrots?",
    "What’s a cat’s favorite color? Purr-ple.",
    "Why do bicycles fall over? Because they are two-tired.",
    "Why don’t oysters share their pearls? Because they’re shellfish.",
    "How do you fix a broken pumpkin? With a pumpkin patch.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the student eat his homework? Because his teacher said it was a piece of cake.",
    "How do you catch a unique rabbit? Unique up on it.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "Why did the astronaut break up with his girlfriend? She needed space.",
    "What did one wall say to the other wall? I'll meet you at the corner.",
    "Why do chicken coops only have two doors? Because if they had four, they’d be chicken sedans.",
    "What do you call a dog that can tell time? A watch dog.",
    "Why was the cookie sad? Because its mom was a wafer so long.",
    "Why was the baby strawberry crying? Because its parents were in a jam.",
    "What did the big bucket say to the little bucket? You look a little pail."
];

function displayRandomJoke() {
    const randomIndex = Math.floor(Math.random() * jokes.length);
    const jokeElement = document.getElementById('joke');
    jokeElement.textContent = jokes[randomIndex];
}

window.onload = displayRandomJoke;
